cwn_relation_labels = dict(
    holonym="整體詞",
    antonym="反義詞",
    meronym="部分詞",
    hypernym="上位詞",
    hyponym="下位詞",
    variant="異體詞",
    nearsynonym="近義詞",
    paranym="類義詞",
    synonym="同義詞",
    varword="異體詞",
    holonym_generic="整體詞_一般性",
    holonym_member="整體詞_成員",
    holonym_substance="整體詞_成份",
    meronym_generic="部分詞_一般性",
    meronym_member="部分詞_成員",
    meronym_substance="部分詞_成份")

pos_label_data = [
    {"pos": "A", "label": "非謂形容詞"},
    {"pos": "Caa", "label": "對等連接詞"},
    {"pos": "Cab", "label": "連接詞"},
    {"pos": "Cba", "label": "連接詞"},
    {"pos": "Cbb", "label": "關聯連接詞"},
    {"pos": "D", "label": "副詞"},
    {"pos": "Da", "label": "數量副詞"},
    {"pos": "DE7", "label": ""},
    {"pos": "Dfa", "label": "動詞前程度副詞"},
    {"pos": "Dfb", "label": "動詞後程度副詞"},
    {"pos": "Di", "label": "時態標記"},
    {"pos": "Dk", "label": "句副詞"},
    {"pos": "FW", "label": "外文標記"},
    {"pos": "I", "label": "感嘆詞"},
    {"pos": "Na", "label": "普通名詞"},
    {"pos": "Nb", "label": "專有名稱"},
    {"pos": "Nc", "label": "地方詞"},
    {"pos": "Ncd", "label": "位置詞"},
    {"pos": "Nd", "label": "時間詞"},
    {"pos": "Nep", "label": "指代定詞"},
    {"pos": "Neqa", "label": "數量定詞"},
    {"pos": "Neqb", "label": "後置數量定詞"},
    {"pos": "Nes", "label": "特指定詞"},
    {"pos": "Neu", "label": "數詞定詞"},
    {"pos": "Nf", "label": "量詞"},
    {"pos": "Ng", "label": "後置詞"},
    {"pos": "Nh", "label": "代名詞"},
    {"pos": "nom", "label": "名物化"},
    {"pos": "P", "label": "介詞"},
    {"pos": "SHI", "label": ""},
    {"pos": "T", "label": "語助詞"},
    {"pos": "V_2", "label": ""},
    {"pos": "VA", "label": "動作不及物動詞"},
    {"pos": "VAC", "label": "動作使動動詞"},
    {"pos": "VB", "label": "動作類及物動詞"},
    {"pos": "VC", "label": "動作及物動詞"},
    {"pos": "VCL", "label": "動作接地方賓語動詞"},
    {"pos": "VD", "label": "雙賓動詞"},
    {"pos": "VE", "label": "動作句賓動詞"},
    {"pos": "VF", "label": "動作謂賓動詞"},
    {"pos": "VG", "label": "分類動詞"},
    {"pos": "VH", "label": "狀態不及物動詞"},
    {"pos": "VHC", "label": "狀態使動動詞"},
    {"pos": "VI", "label": "狀態類及物動詞"},
    {"pos": "VJ", "label": "狀態及物動詞"},
    {"pos": "VK", "label": "狀態句賓動詞"},
    {"pos": "VL", "label": "狀態謂賓動詞"},
]

cwn_pos_labels = {x["pos"]: x["label"] for x in pos_label_data}
